--DROP DATABASE AuctionNet;
--GO
CREATE DATABASE AuctionNet
GO
USE AuctionNet
GO

CREATE TABLE AuctionHistory
(
Id INT PRIMARY KEY IDENTITY(1,1),
AuctionNumber INT NOT NULL,
ProductName NVARCHAR(50) NOT NULL,
SuplierName NVARCHAR(50) NOT NULL,
CustomerName VARCHAR(50) NOT NULL,
StartPrice DECIMAL NOT NULL,
EndPrice DECIMAL NOT NULL,
);

CREATE TABLE Customers(
Id INT PRIMARY KEY IDENTITY (1,1),
Name NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,
Phone NVARCHAR(20) NOT NULL,
);

CREATE TABLE Suppliers(
Id INT PRIMARY KEY IDENTITY (1,1),
Name NVARCHAR(50) NOT NULL,
Phone NVARCHAR(20) NOT NULL,
);

CREATE TABLE Products(
Id INT PRIMARY KEY IDENTITY(1,1),
ProductName NVARCHAR(50) NOT NULL,
Description NVARCHAR(200) NOT NULL,
StartPrice DECIMAL NOT NULL,
Commission DECIMAL(5,2) NOT NULL,
SupplierId INT NOT NULL,
CONSTRAINT FK_Product_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id)
);

CREATE TABLE Auctions(
Id INT PRIMARY KEY IDENTITY(1,1),
AcceptPrice DECIMAL NOT NULL,
StartTime DATETIME NOT NULL,
EndTime DATETIME NOT NULL,
ProductId INT NOT NULL,
CONSTRAINT FK_Auctions_Products FOREIGN KEY (ProductId) REFERENCES Products(Id)
);

CREATE TABLE Bids(
Id INT PRIMARY KEY IDENTITY(1,1),
CustomerId INT,
AuctionId INT,
Bid DECIMAL NOT NULL,
Date DATETIME NOT NULL,
CONSTRAINT FK_Bids_Customers FOREIGN KEY (CustomerId) REFERENCES Customers(Id),
CONSTRAINT FK_Bids_Auctions FOREIGN KEY (AuctionId) REFERENCES Auctions(Id),
);

